"""add_ride_feature_location_and_cancellation_fields

Revision ID: 3c8f1456272b
Revises: 115cb637c531
Create Date: 2026-03-05 06:24:37.955227
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8f1456272b'
down_revision: Union[str, None] = '115cb637c531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable PostGIS for ST_DWithin driver proximity queries
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_locations')
    op.add_column('driver_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('driver_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('driver_profiles', sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rides', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rides', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.add_column('rides', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'rides', 'users', ['cancelled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_column('rides', 'cancellation_reason')
    op.drop_column('rides', 'cancelled_by')
    op.drop_column('rides', 'cancelled_at')
    op.drop_column('driver_profiles', 'last_location_update')
    op.drop_column('driver_profiles', 'longitude')
    op.drop_column('driver_profiles', 'latitude')
    op.create_table('driver_locations',
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], name=op.f('driver_locations_driver_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('driver_id', name=op.f('driver_locations_pkey'))
    )
    # ### end Alembic commands ###
