"""driver_onboarding_updates

Revision ID: 582a37ba071c
Revises: 4cf65afc9a8d
Create Date: 2026-02-21 16:17:15.774516
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '582a37ba071c'
down_revision: Union[str, None] = '4cf65afc9a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create new enums (checkfirst in case of partial previous run)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE verificationstatus AS ENUM ('NOT_STARTED', 'PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE documentstatus AS ENUM ('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)

    # Drop if partially created from a failed run
    op.execute("DROP TABLE IF EXISTS driver_documents")

    # Create driver_documents table
    op.create_table('driver_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='documentstatus', create_type=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Delete existing driver profiles and vehicles (fresh start for onboarding restructure)
    op.execute("DELETE FROM vehicle_details")
    op.execute("DELETE FROM driver_profiles")

    # Update driver_profiles: add new columns, drop old ones
    op.add_column('driver_profiles', sa.Column('license_number', sa.String(length=50), nullable=False))
    op.add_column('driver_profiles', sa.Column('license_expiry', sa.Date(), nullable=False))
    op.add_column('driver_profiles', sa.Column('vehicle_type', sa.String(length=20), nullable=True))
    op.add_column('driver_profiles', sa.Column('verification_status', postgresql.ENUM('NOT_STARTED', 'PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='verificationstatus', create_type=False), nullable=False, server_default='PENDING'))
    op.add_column('driver_profiles', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('driver_profiles', 'licence_url')
    op.drop_column('driver_profiles', 'profile_status')
    op.drop_column('driver_profiles', 'identity_url')

    # Update vehicle_details: add new columns, drop old ones
    op.add_column('vehicle_details', sa.Column('license_plate', sa.String(length=20), nullable=False))
    op.add_column('vehicle_details', sa.Column('make', sa.String(length=50), nullable=False))
    op.add_column('vehicle_details', sa.Column('model', sa.String(length=50), nullable=False))
    op.add_column('vehicle_details', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('vehicle_details', sa.Column('passenger_capacity', sa.Integer(), nullable=True))
    op.add_column('vehicle_details', sa.Column('has_air_conditioning', sa.Boolean(), nullable=True))
    op.add_column('vehicle_details', sa.Column('provides_helmet', sa.Boolean(), nullable=True))
    op.drop_constraint('vehicle_details_plate_number_key', 'vehicle_details', type_='unique')
    op.create_unique_constraint('vehicle_details_license_plate_key', 'vehicle_details', ['license_plate'])
    op.drop_column('vehicle_details', 'plate_number')
    op.drop_column('vehicle_details', 'vehicle_name')
    op.drop_column('vehicle_details', 'image_url')

    # Drop old enum
    op.execute("DROP TYPE IF EXISTS profilestatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_details', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('vehicle_details', sa.Column('vehicle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vehicle_details', sa.Column('plate_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicle_details', type_='unique')
    op.create_unique_constraint(op.f('vehicle_details_plate_number_key'), 'vehicle_details', ['plate_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('vehicle_details', 'provides_helmet')
    op.drop_column('vehicle_details', 'has_air_conditioning')
    op.drop_column('vehicle_details', 'passenger_capacity')
    op.drop_column('vehicle_details', 'year')
    op.drop_column('vehicle_details', 'model')
    op.drop_column('vehicle_details', 'make')
    op.drop_column('vehicle_details', 'license_plate')
    op.add_column('driver_profiles', sa.Column('identity_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('driver_profiles', sa.Column('profile_status', postgresql.ENUM('PENDING', 'ACTIVE', 'DEACTIVATED', 'REJECTED', name='profilestatus'), autoincrement=False, nullable=False))
    op.add_column('driver_profiles', sa.Column('licence_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('driver_profiles', 'submitted_at')
    op.drop_column('driver_profiles', 'verification_status')
    op.drop_column('driver_profiles', 'vehicle_type')
    op.drop_column('driver_profiles', 'license_expiry')
    op.drop_column('driver_profiles', 'license_number')
    op.drop_table('driver_documents')
    # ### end Alembic commands ###
